---
include:
  - config/dev/ory.compose.yaml

volumes:
  pgdata: {}

services:
  db:
    image: postgres:17
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data
      - ./config/dev/psql:/docker-entrypoint-initdb.d:ro
